int rt_key_ctl_init(void);

#ifndef		KEY_STATE_TYPE_MACRO
#define		KEY_STATE_TYPE_MACRO
enum KEY_STATE_TYPE{
KEY_STATE_NONE,
	KEY_STATE_RECORD,
	KEY_STATE_PAUSE,
	KEY_STATE_PREV,
	KEY_STATE_NEXT,
	KEY_STATE_PLAYER,
KEY_STATE_INIT,

};
#endif

